### ISSUE TITLE
Sending Notifications

### ISSUE THREAD

**Issue by AWZRD** [adipasquale/passe-passe#1]
Hey Dude Thanks For This!

Do you by chance know how you could send notifications to passes? Or how to get the push token from the device? I tried reading the developer guide but they make me feel dumb. I'd appreciate it! Thanks

- Amissi

**Comment by adipasquale** [comment]
Hi @AWZRD! sorry but I have had 0 experience with Apple Passes before and since that point in time where I worked on this so I won't be able to help :/ Apple docs are a complete dump so hang in there and best of luck! 💪
